[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"
  base = "app/"

[dev]
  command = "yarn start"
  targetPort = 3000
  functionsPort = 8081
  framework = "#custom"

[[redirects]]
  from = "/send/*"
  to = "/.netlify/functions/send/"
  status = 200